[config]
schemaVersion = "1.0.0"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "chrispavs"
name = "AutoStart"
description = "Automatically load into a lobby when the game starts. Save time clicking buttons! Online by default. You can choose to start in offline mode via mod's config."
websiteUrl = "https://github.com/chrispavs/peak-auto-start"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/AutoStart/release/chrispavs.AutoStart.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", ]
